let fDict={
"meanSentenceLength":  "average sentence length",
"meanWordLength":  "average word length",
"sentences":  "number of sentences",
"totalGI":  "number of known words",
"wordsCASED":  "words in uppercase",
"wordscased":  "words in lowercase",
"wordsCaSeD":  "words with non-standard letter case",
"wordsCased":  "words in title case",
"TNoun":  "noun",
"TSingular":  "noun in singular",
"TProperNoun":  "proper noun",
"TPlural":  "noun in plural",
"TUncountable":  "uncountable noun",
"TPronoun":  "pronoun",
"TPossessive":  "possesive pronoun",
"TVerb":  "verb",
"TPresentTense":  "verb in present tense",
"TInfinitive":  "verb in infinitive",
"TGerund":  "verb in gerund",
"TPastTense":  "past form of verb",
"TPerfectTense":  "past participle",
"TFuturePerfect":  "future perfect form",
"TPluperfect":  "pluperfect verb form",
"TCopula":  "copula",
"TModal":  "modal verb",
"TParticiple":  "participle",
"TParticle":  "particle",
"TValue":  "value",
"TAdjective":  "adjective",
"TComparable":  "comparable adjective",
"TComparative":  "adjective in comparative",
"TSuperlative":  "adjective in superlative",
"TContraction":  "contraction",
"TAdverb":  "adverb",
"TDeterminer":  "determiner",
"TConjunction":  "conjunction",
"TPreposition":  "preposition",
"TQuestionWord":  "question word",
"TPronoun":  "pronoun",
"TAuxiliary":  "auxiliary",
"TNegative":  "negative",
"T?":  "unknown",
"TNull":  "no-word",
"catGIpositiv":  "words of positive outlook (and similar)",
"catGInegativ":  "words of negative outlook (and similar)",
"catGIpstv":  "positive words (and similar)",
"catGIaffil":  "words indicating affiliation or supportiveness (and similar)",
"catGIngtv":  "negative words (and similar)",
"catGIhostile":  "words related to hostility or aggressiveness (and similar)",
"catGIstrong":  "words implying strength (and similar)",
"catGIpower":  "words indicating a concern with power or authority (and similar) ",
"catGIweak":  "words implying weakness (and similar)",
"catGIsubmit":  "words connoting submission to authority or power (and similar)",
"catGIactive":  "words implying an active orientation (and similar)",
"catGIpassive":  "words indicating a passive orientation (and similar)",
"catGIpleasur":  "words indicating the enjoyment of a feeling (and similar)",
"catGIpain":  "words indicating suffering, lack of confidence, or commitment (and similar)",
"catGIfeel":  "words describing feelings other than pain or pleasure (and similar)",
"catGIarousal":  "words indicating excitation (and similar)",
"catGIemot":  "words related to emotion (and similar)",
"catGIvirtue":  "words indicating an assessment of moral approval (and similar)",
"catGIvice":  "words indicating an assessment of moral disapproval (and similar)",
"catGIovrst":  "words indicating emphasis in assessment (and similar)",
"catGIundrst":  "words indicating lack of emphasis in assessment (and similar)",
"catGIacadem":  "words relating to academic matters (and similar)",
"catGIdoctrin":  "words referring to organized systems of belief or knowledge (and similar)",
"catGIecon@":  "words of an economic or commercial orientation (and similar)",
"catGIexch":  "words concerned with buying, selling and trading (and similar)",
"catGIecon":  "words of an economic or commercial orientation (and similar)",
"catGIexprsv":  "words associated with the arts and sports (and similar)",
"catGIlegal":  "words relating to legal matters (and similar)",
"catGImilit":  "words relating to military matters (and similar)",
"catGIpolit@":  "words having a political character (and similar)",
"catGIpolit":  "words having a political character (and similar)",
"catGIrelig":  "words pertaining to religious matters (and similar)",
"catGIrole":  "words referring to human roles (and similar)",
"catGIcoll":  "words referring to human collectivities (and similar)",
"catGIwork":  "words for socially defined ways for doing work (and similar)",
"catGIritual":  "words for social rituals (and similar)",
"catGIsocrel":  "words for interpersonal relations (and similar)",
"catGIrace":  "words referring to racial or ethnic characteristics (and similar)",
"catGIkin@":  "terms denoting kinship (and similar) ",
"catGImale":  "words referring to men and social roles associated with men (and similar)",
"catGIfemale":  "words referring to women and social roles associated with women (and similar)",
"catGInonadlt":  "words associated with children (and similar)",
"catGIhu":  "general references to humans (and similar)",
"catGIani":  "references to animals (and similar)",
"catGIplace":  "words referring to places (and similar)",
"catGIsocial":  "words for locations for social interaction (and similar)",
"catGIregion":  "words describing regions and areas (and similar)",
"catGIroute":  "words referring to routes (and similar)",
"catGIaquatic":  "words referring to locations related to water (and similar)",
"catGIland":  "words for places occurring in nature (and similar)",
"catGIsky":  "words for aerial spaces and objects (and similar)",
"catGIobject":  "words for describing physical objects (and similar)",
"catGItool":  "words referring to tools (and similar)",
"catGIfood":  "words describing food (and similar)",
"catGIvehicle":  "words describing vehicles (and similar)",
"catGIbldgpt":  "words for buildings and their parts (and similar)",
"catGIcomnobj":  "words for the tools of communication (and similar)",
"catGInatobj":  "words for natural objects (and similar)",
"catGIbodypt":  "words for body parts (and similar)",
"catGIcomform":  "words relating to communication (and similar)",
"catGIcom":  "communication words (and similar)",
"catGIsay":  "words referring to talking (and similar)",
"catGIneed":  "words related to the expression of need (and similar)",
"catGIgoal":  "names of goals and aims (and similar)",
"catGItry":  "words indicating activities to reach a goal (and similar)",
"catGImeans":  "words denoting objects or acts utilized in attaining goals (and similar)",
"catGIpersist":  "words indicating endurance (and similar)",
"catGIcomplet":  "words indicating achievement of goals (and similar)",
"catGIfinish":  "words indication termination of an action (and similar)",
"catGIfail":  "words indicating failure (and similar)",
"catGInatrpro":  "words for processes found in nature (and similar)",
"catGIbegin":  "words for beginnings of processes (and similar)",
"catGIvary":  "words indicating change (and similar)",
"catGIincreas":  "words referring to processes of increase (and similar)",
"catGIdecreas":  "words referring to processes of decrease (and similar)",
"catGIstay":  "words referring to actions of keeping a current state (and similar)",
"catGIrise":  "words referring to actions of rising (and similar)",
"catGIexert":  "words related to exerting influence (and similar)",
"catGIfetch":  "words for fetchying and carrying (and similar)",
"catGItravel":  "words for physical movement and travel (and similar)",
"catGIfall":  "words related to falling (and similar)",
"catGIthink":  "words referring to the thought processes (and similar)",
"catGIknow":  "words indicating properties of mental classes, concepts or ideas (and similar)",
"catGIcausal":  "words denoting causal relationships (and similar)",
"catGIought":  "words indicating moral imperative (and similar)",
"catGIperceiv":  "words referring to the process of perceiving (and similar)",
"catGIcompare":  "words of comparison (and similar)",
"catGIeval@":  "words which imply judgment and evaluation (and similar)",
"catGIeval":  "evaluative words (and similar)",
"catGIsolve":  "words associated with problem solving (and similar)",
"catGIabs@":  "abstract vocabulary (and similar)",
"catGIabs":  "abstract vocabulary (and similar)",
"catGIquality":  "words indicating qualities or degrees of qualities (and similar)",
"catGIquan":  "words indicating the assessment of quantity (and similar)",
"catGInumb":  "words for numbers (and similar)",
"catGIord":  "ordinal words (and similar)",
"catGIcard":  "cardinal words (and similar)",
"catGIfreq":  "words indicating an assessment of frequency (and similar)",
"catGIdist":  "words referring to distance and its measures (and similar)",
"catGItime@":  "words indicating a time consciousness (and similar)",
"catGItime":  "time expressions (and similar words)",
"catGIspace":  "words indicating a location in space (and similar)",
"catGIpos":  "words indication position in space (and similar)",
"catGIdim":  "words for dimensions (and similar)",
"catGIrel":  "words indicating relationships between entities (and similar)",
"catGIcolor":  "words of color (and similar)",
"catGIself":  "pronouns referring to the singular self (and similar words)",
"catGIour":  "pronouns referring to the inclusive self (and similar words)",
"catGIyou":  "pronouns for addressing directly another person (and similar words)",
"catGIname":  "proper names (and similar words)",
"catGIyes":  "words directly indicating agreement (and similar)",
"catGIno":  "words directly indicating disagreement (and similar)",
"catGInegate":  "words that refer to reversal or negation (and similar)",
"catGIintrj":  "interjection words (and similar)",
"catGIiav":  "verbs giving an interpretative explanation (and similar words)",
"catGIdav":  "verbs of simple actions (and similar words)",
"catGIsv":  "verbs describing mental or emotional states (and similar words)",
"catGIipadj":  "adjectives referring to relations between people (and similar words)",
"catGIindadj":  "adjectives describing people (and similar words)",
"catGIpowgain":  "words about power increasing (and similar)",
"catGIpowloss":  "words of power decreasing (and similar)",
"catGIpowends":  "words about the goals of the power process (and similar)",
"catGIpowaren":  "words referring to political places and environments (and similar)",
"catGIpowcon":  "words for ways of conflicting (and similar)",
"catGIpowcoop":  "words for ways of cooperating (and similar)",
"catGIpowaupt":  "words for individual and collective actors in power process (and similar)",
"catGIpowpt":  "words for non-authoritative actors in the power process (and similar)",
"catGIpowdoct":  "words for recognized ideas about power (and similar)",
"catGIpowauth":  "words concerned with a tools or forms of invoking power (and similar)",
"catGIpowoth":  "words related to power (and similar)",
"catGIpowtot":  "words related to power (and similar)",
"catGIrcethic":  "words of values concerning the social order (and similar)",
"catGIrcrelig":  "words related to religion (and similar)",
"catGIrcgain":  "words related to moral gains (and similar)",
"catGIrcloss":  "words related to moral losses (and similar)",
"catGIrcends":  "words related to moral goals (and similar)",
"catGIrctot":  "words related to moral values (and similar)",
"catGIrspgain":  "words for the garnering of respect (and similar)",
"catGIrsploss":  "words for the losing of respect (and similar)",
"catGIrspoth":  "words related to respect (and similar)",
"catGIrsptot":  "words related to respect (and similar)",
"catGIaffgain":  "words for reaping affect (and similar)",
"catGIaffloss":  "words for affect loss and indifference (and similar)",
"catGIaffpt":  "words for affect participants (and similar)",
"catGIaffoth":  "words in the affect domain (and similar)",
"catGIafftot":  "words in the affect domain (and similar)",
"catGIwltpt":  "words for various roles in business and commerce (and similar)",
"catGIwlttran":  "words for exchange of wealth (and similar)",
"catGIwltoth":  "words related to wealth (and similar)",
"catGIwlttot":  "words related to wealth (and similar)",
"catGIwlbgain":  "words related to a gain in well-being (and similar)",
"catGIwlbloss":  "words related to a loss in a state of well-being (and similar)",
"catGIwlbphys":  "words connoting the physical well-being (and similar)",
"catGIwlbpsyc":  "words connoting the psychological well-being (and similar)",
"catGIwlbpt":  "words for roles realted to well-being (and similar)",
"catGIwlbtot":  "words in well-being domain (and similar)",
"catGIenlgain":  "words reflecting a gain in enlightenment (and similar)",
"catGIenlloss":  "words reflecting a loss in enlightenment (and similar)",
"catGIenlends":  "words denoting pursuit of enlightenment (and similar)",
"catGIenlpt":  "words referring to roles in the enlightenment sphere (and similar)",
"catGIenloth":  "words related to enlightenment (and similar)",
"catGIenltot":  "words related to enlightenment (and similar)",
"catGIsklasth":  "words related to the arts (and similar)",
"catGIsklpt":  "words about trades and professions (and similar)",
"catGIskloth":  "skill-related words (and similar)",
"catGIskltot":  "skill-related words (and similar)",
"catGItrngain":  "words of accomplishment (and similar)",
"catGItrnloss":  "words of not accomplishing (and similar)",
"catGItranlw":  "words of transaction or exchange (and similar)",
"catGImeanslw":  "words referring to means and utility  (and similar)",
"catGIendslw":  "words of ends or goals (and similar)",
"catGIarenalw":  "words for settings and artenas (and similar)",
"catGIptlw":  "words for actors (and similar)",
"catGInation":  "words for nations (and similar)",
"catGIanomie":  "words showing a lack of preference (and similar)",
"catGInegaff":  "words of negative affect (and similar)",
"catGIposaff":  "words of popsitive affect (and similar)",
"catGIsurelw":  "words indicating a feeling of certainty (and similar)",
"catGIif":  "words denoting feelings of uncertainty, doubt and vagueness (and similar)",
"catGInotlw":  "words that show a denial (and similar)",
"catGItimespc":  "words related to space or time (and similar)",
"catGIformlw":  "words referring to formats and conventions of communication (and similar)"
}

function featureDescription(featureName){
	if (featureName.startsWith('TAG_')){
		let parts=featureName.split('_');
		if (parts.length==2){
			return("part of speech: "+fDict['T'+parts[1]]);
		}
		if (parts.length==3){
			return("part of speech sequence: "+fDict['T'+parts[1]]+", "+fDict['T'+parts[2]]);
		}
		if (parts.length==4){
			return("part of speech sequence: "+fDict['T'+parts[1]]+", "+fDict['T'+parts[2]]+", "+fDict['T'+parts[3]]);
		}
	}else{
		return(fDict[featureName]);
	}
}
